export const USER_TYPES_FOR_MODAL = 'USER_TYPES_FOR_MODAL';
export const DELETE_EMAILS = 'DELETE_EMAILS';
export const REGISTRATION_FOR = 'REGISTRATION_FOR';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
